# system message
[InfoNotFound]
other = "信息未找到"

[InternalError]
other = "服务器内部错误"

[InvalidArgument]
other = "参数错误"

[Unavailable]
other = "服务器不可用"

# gin
[GinStartFail]
other = "无法启动gin"

# consul resolver
[GrpcConsulResolverStartFail]
other = "启动grpc-consul-resolver失败"

[FailStartConsul]
other = "初始化consul失败"

[FailListenConsul]
other = "监听consul服务失败"

[FailRegisterConsul]
other = "注册服务失败"

[FailGetService]
other = "获取服务失败"

# gin api user
[WrongPassword]
other = "密码错误"

[FailRegister]
other = "注册失败"

[AlreadyExist]
other = "用户名已存在"

[LoginSuccess]
other = "登录成功"

# api captcha
[WrongCaptcha]
other = "验证码错误"

#validator translator
[FailRegisterTrans]
other = "注册验证器翻译器失败"

